run:

linters-settings:
  maligned:
    suggest-new: true
  gocritic:
    disabled-checks:
      - singleCaseSwitch
  funlen:
    lines: 100
    statements: 50

linters:
  disable:
    - gochecknoglobals
    - testpackage
    #- gomnd
    - exhaustive
    - forbidigo
  enable-all: true
