version: '3'

services:
  mariadb:
    image: mariadb:10.5.8
    command: --init-file /srv/sql/init.sql
    volumes:
      - ./dbuitl:/srv/sql/
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=airdb
      - MYSQL_PASSWORD=airdb
    container_name: mariadb
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    container_name: redis